<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\service\MailerService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\AppBundle\\service\\MailerService.php';

return $this->services['AppBundle\service\MailerService'] = new \AppBundle\service\MailerService(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load('getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, 'khlifizouhaier9@gmail.com', ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'});
