<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.5xtv_tx' shared service.

return $this->services['service_locator.5xtv_tx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('mailerService' => function () {
    $f = function (\AppBundle\service\MailerService $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\service\MailerService']) ? $this->services['AppBundle\service\MailerService'] : $this->load('getMailerServiceService.php')) && false ?: '_'});
}));
