<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \AppBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'prenom', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'passeport', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'cin', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'ribBancaire', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'dateNaissance', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'dateEmploie', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'adresseMail', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'adresseVille', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'numeroTelephone', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'etatCivil', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'etatFamilial', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'bilans_responsable', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'employe_ratings', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'liste_candidature', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'departement_associe', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'evennements_proposes', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'evennements_adheres', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'photo_profil', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'roles'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'prenom', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'passeport', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'cin', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'ribBancaire', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'dateNaissance', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'dateEmploie', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'adresseMail', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'adresseVille', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'numeroTelephone', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'etatCivil', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'etatFamilial', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'bilans_responsable', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'employe_ratings', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'liste_candidature', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'departement_associe', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'evennements_proposes', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'evennements_adheres', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'photo_profil', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'roles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', []);

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', [$usernameCanonical]);

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', []);

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', [$emailCanonical]);

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', []);

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($plainPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', [$plainPassword]);

        return parent::setPlainPassword($plainPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', []);

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$cin]);

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEmploie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEmploie', []);

        return parent::getDateEmploie();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEmploie($dateEmploie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEmploie', [$dateEmploie]);

        return parent::setDateEmploie($dateEmploie);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseMail', []);

        return parent::getAdresseMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseMail($adresseMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseMail', [$adresseMail]);

        return parent::setAdresseMail($adresseMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseVille', []);

        return parent::getAdresseVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseVille($adresseVille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseVille', [$adresseVille]);

        return parent::setAdresseVille($adresseVille);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatFamilial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatFamilial', []);

        return parent::getEtatFamilial();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatFamilial($etatFamilial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatFamilial', [$etatFamilial]);

        return parent::setEtatFamilial($etatFamilial);
    }

    /**
     * {@inheritDoc}
     */
    public function getBilansResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBilansResponsable', []);

        return parent::getBilansResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setBilansResponsable($bilans_responsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBilansResponsable', [$bilans_responsable]);

        return parent::setBilansResponsable($bilans_responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasseport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasseport', []);

        return parent::getPasseport();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasseport($passeport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasseport', [$passeport]);

        return parent::setPasseport($passeport);
    }

    /**
     * {@inheritDoc}
     */
    public function getRibBancaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRibBancaire', []);

        return parent::getRibBancaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setRibBancaire($ribBancaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRibBancaire', [$ribBancaire]);

        return parent::setRibBancaire($ribBancaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTelephone', []);

        return parent::getNumeroTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTelephone($numeroTelephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTelephone', [$numeroTelephone]);

        return parent::setNumeroTelephone($numeroTelephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatCivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatCivil', []);

        return parent::getEtatCivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatCivil($etatCivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatCivil', [$etatCivil]);

        return parent::setEtatCivil($etatCivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeRatings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeRatings', []);

        return parent::getEmployeRatings();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeRatings($employe_ratings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeRatings', [$employe_ratings]);

        return parent::setEmployeRatings($employe_ratings);
    }

    /**
     * {@inheritDoc}
     */
    public function getListeCandidature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListeCandidature', []);

        return parent::getListeCandidature();
    }

    /**
     * {@inheritDoc}
     */
    public function setListeCandidature($liste_candidature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListeCandidature', [$liste_candidature]);

        return parent::setListeCandidature($liste_candidature);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartementAssocie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartementAssocie', []);

        return parent::getDepartementAssocie();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartementAssocie($departement_associe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartementAssocie', [$departement_associe]);

        return parent::setDepartementAssocie($departement_associe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvennementsProposes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvennementsProposes', []);

        return parent::getEvennementsProposes();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvennementsProposes($evennements_proposes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvennementsProposes', [$evennements_proposes]);

        return parent::setEvennementsProposes($evennements_proposes);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvennementsAdheres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvennementsAdheres', []);

        return parent::getEvennementsAdheres();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvennementsAdheres($evennements_adheres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvennementsAdheres', [$evennements_adheres]);

        return parent::setEvennementsAdheres($evennements_adheres);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoProfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoProfil', []);

        return parent::getPhotoProfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoProfil($photo_profil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoProfil', [$photo_profil]);

        return parent::setPhotoProfil($photo_profil);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$role]);

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', []);

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', [$role]);

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', []);

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', []);

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', []);

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isSuperAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuperAdmin', []);

        return parent::isSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', [$role]);

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', [$boolean]);

        return parent::setSuperAdmin($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $time = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', [$time]);

        return parent::setLastLogin($time);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', [$confirmationToken]);

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', [$date]);

        return parent::setPasswordRequestedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', []);

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isPasswordRequestNonExpired($ttl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPasswordRequestNonExpired', [$ttl]);

        return parent::isPasswordRequestNonExpired($ttl);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', []);

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNames', []);

        return parent::getGroupNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGroup($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGroup', [$name]);

        return parent::hasGroup($name);
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', [$group]);

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', [$group]);

        return parent::removeGroup($group);
    }

}
